### ISSUE TITLE
Handling malicious users

### ISSUE THREAD

**Issue by williambogaiv** [ritterim/definely#52]
I am opening discussion to @ritterim/developers, @ritterim/owners, and @ritterim/qa, for a way to avoid malicious users from going through the app. and randomly updating terms. I have a few suggestions and would like to hear from others. The plan is to leave this open until **1/30/2015**. Afterwards, the most-favored implementation will be completed.

In no particular order:
  - Require CAPCHA - this will not directly prevent someone from maliciously editing content, but may be enough deterrent. However, this could also slow-down adoption of the app. since we would introduce another hurdle to creation.
  - Keep historical log of changes - this would allow someone to see changes to a term. However, updating the existing `weightedVector` field on the `terms` table would also need to account for all changes. This has less deterrent (and does not prevent malicious editing), but still allows access to previously unkept data.
  - **Make terms immutable - this removes the Wiki-style aspect from the app., but *does* prevent any record from being edited. A weakness is the potential for an increase in similar terms due to slight changes needed to existing content. However, tweaks to search results could favor the most-desirable records while pushing old ones to the bottom.**
  - Assign a code to each term which is required in order to edit a term. This code would be delivered to the user who created the term (inline, email, SMS, etc). Anyone with knowledge of the code can make changes (maybe even to the code itself). Therefore, the initial creator has sole discretion whether to make it public.
  - Do nothing. Let users continue to freely edit content under the premise the app. is not currently popular enough to attract unwanted attention. This requires the least amount of work, but opens the door for quick destruction of curated data, which could also lead to abandonment of the app.

**Comment by kendaleiv** [comment]
If we go the CAPTCHA route, honeypot field(s) may provide enough bot protection, without detracting from the user experience.

If it 'should' be secured for changes, perhaps an authentication method is warranted?

**Comment by dsagang** [comment]
I think assigning a code to each term is the best option in this case because it is secured in the sense that it determines some privilege to update the terms. So it is also flexible.

**Comment by TimGIMT** [comment]
If we choose any method then I would agree with @dsagang and choose a code for each term

**Comment by kendaleiv** [comment]
What problems is this attempting to address?

If it's attempting to address *malicious users* and *spam bots* from creating a modifying data, a secret key per term strategy will permit the database to be polluted with unwanted new entries (unless, it also requires a secret key during creation). Also, if unwanted items are able to be created, legitimate users will be unable to modify the spam entries without the secret key (and, I'm not aware of user-facing delete functionality at this time).

Having a password per entry is logistically difficult for users to manage, and will likely lead to users not contributing due to hassle.

**Comment by williambogaiv** [comment]
@kendaleiv, the concern isn't unwanted items, it's preventing good results from being altered. I have updated my initial issue-text to highlight my preference for immutability. At this point, any truly unwanted items would have to be removed manually from the DB.

**Comment by williambogaiv** [comment]
And, the option for doing nothing might be good-enough if the app.'s data is transient or if the app. is hosted as internal-only.

Thought of another option: Basic HTTP Auth. – no changes are necessary to the app. and it would limit the pool of users. However, just hosting internally could achieve the same thing.

**Comment by ironpilot** [comment]
I would at least go with a digest auth if you're talking server authentication. Even being an internal tool, this would help to obscure any passwords entered into the system and it's the same deployment method as basic auth.

**Comment by williambogaiv** [comment]
It's mid-week. Two more days to get those suggestions in. Thanks for the feedback so far.

**Comment by ScottSchwalm** [comment]
@williambogaiv why no Google survey for this?

**Comment by williambogaiv** [comment]
GitHub allows for better back-and-forth communication (i.e. our banter).

**Comment by khalidabuhakmeh** [comment]
I think I'm fine with keeping this the way it is for now. If it becomes an issue we can address it later.
