### ISSUE TITLE
New lines in Definition fields are not being displayed

### ISSUE THREAD

**Issue by kendaleiv** [ritterim/definely#53]
For an example, navigate to http://definely.ritterim.com/terms/12

**Comment by williambogaiv** [comment]
Now might be a good time to introduce Markdown middleware. It was on my list of todos over the weekend – just didn't get to it in time.

**Comment by williambogaiv** [comment]
Expected output (contains `\n`):
![image](https://cloud.githubusercontent.com/assets/3382469/5906371/02eb364a-a565-11e4-96a6-362fb0fd78b4.png)

Actual output (`\n` preserved in the output, but should be `<br />`):
![image](https://cloud.githubusercontent.com/assets/3382469/5906382/1ea8471a-a565-11e4-800b-bc3fbc5e3d96.png)

**Comment by williambogaiv** [comment]
Confirmed new lines are appearing as-expected:
![image](https://cloud.githubusercontent.com/assets/3382469/5908812/ccefd2e4-a578-11e4-908e-9e420c40907e.png)
