### ISSUE TITLE
Add legend for search result icons

### ISSUE THREAD

**Issue by williambogaiv** [ritterim/definely#58]
Looking for feedback on possible inclusion of legend related to search result iconography. Existing behavior just shows a colored icon beside the search result. New behavior gives description of each color on the bottom of the search results:

![image](https://cloud.githubusercontent.com/assets/3382469/5912285/c7d894a4-a59f-11e4-80ee-3d0173d52a18.png)

**Comment by TimGIMT** [comment]
@williambogaiv How about Excellent, Good, Fair and Poor and how about the use of emoticons like :sparkles: :+1: :exclamation: :imp: :cry:  I think you get the point ;)  ?

**Comment by kendaleiv** [comment]
Do they need to be grouped? Could we simply order them by relevance and remove this concept altogether?

**Comment by allenbrubaker** [comment]
I like the legend; however, I feel like that 'What do these '[book icon]' mean?' is kind of superfluous.  I like the look of the legend without that extra verbiage.

**Comment by williambogaiv** [comment]
@kendaleiv, they are ordered by relevance. Since we currently only show the term's name, the idea was to give some distinction between results. Maybe that's the wrong path. Maybe we should show part of the description matching the search (i.e. what search engines currently do).

**Comment by williambogaiv** [comment]
Going to close this issue as the UI is going in a different direction. I'm going to make it easier to search and add terms from any page.

**Comment by williambogaiv** [comment]
Adding new related issue: https://github.com/ritterim/definely/issues/59
