### ISSUE TITLE
Add model definitions

### ISSUE THREAD

**Issue by williambogaiv** [ritterim/definely#8]
Not sure how using [siren spec.](https://github.com/kevinswiber/siren) will alter the idea of models. But for now, we need a couple models which mirror the [existing DB-schema](https://github.com/ritterim/definely/issues/6).

**Comment by allenbrubaker** [comment]
Already added Term model.

**Comment by williambogaiv** [comment]
This was added with https://github.com/ritterim/definely/pull/23.
